server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SouravBanerje/microservice-config.git
          clone-on-start: true

